all: legoman legoman2

legoman:
	g++ -o examen examen.cpp model.cpp -lglut -lGLU -lGL
	g++ -c examen.cpp model.cpp -lglut -lGLU -lGL
legoman2:
	g++ -o examen2 examen2.cpp model.cpp -lglut -lGLU -lGL
	g++ -c examen2.cpp model.cpp -lglut -lGLU -lGL